### ISSUE TITLE
Try.Net examples throw compilation error

### ISSUE THREAD

**Issue by dhymik** [nodatime/nodatime.org#115] opened 2021-11-27 09:14 UTC
I am trying to test the examples on [this examples page](https://nodatime.org/3.0.x/userguide/recipes) in the provided test window.

After copying code (by clicking on one of the provided "copy to editor" buttons) and clicking "Run", I see "Running..." in the output display indefinitely. After clicking "Run a second time, I get  "CompilationError" in the Output display.

**Comment by malcolmr** [comment] 2021-11-27 09:28
fwiw, this may very well be a Try.Net problem: their JS is generating POST requests that are failing with a 400 Bad Request (but unfortunately no other details). I'm not sure if Try.Net's API _is_ actually documented anywhere (AIUI it's still in private preview), so we might need support from someone on that side to debug this.

**Comment by jskeet** [comment] 2021-11-27 09:32
Hopefully my contacts in the team haven't moved on :)

**Comment by malcolmr** [comment] 2022-11-23 10:33
Duplicate of #100.

**Closed by malcolmr** 2022-11-23 10:33 UTC
